
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
  #namespace: go
  labels:
    app: goapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goapi
  template:
    metadata:
      labels:
        app: goapi
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: goapi
        # image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        image: go-server:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: go-service
  #namespace: go
spec:
  selector:
    app: goapi
  type: ClusterIP
  ports:
    - name: ingress
      protocol: TCP
      port: 80
      targetPort: 80


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  #namespace: go
  name: go-ingress
  annotations:
    allow.http: "false"
spec:
  rules:
  - host: go.rancher.jaru.ro.gov.br
    http:
      paths:
        - path: /
          pathType: Exact
          backend:
            service:
              name: go-service
              port:
                name: ingress
